### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by gswycf** [chevalierNoir/OpenASL#5]
Hi, i follow your readme, but can not download dataset, do you have another way to download dataset? e.g, google drive? baidu drive?

"[youtube] 1qMSlb1sbXw: Downloading webpage
[youtube] 1qMSlb1sbXw: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with t
he --verbose flag and include its complete output.
  4%|█████▌                                                                                                                                                       | 73/2043 [04:00<1:56:01,  3.53s/it]G
:\dataset\openasl\OpenASL-main\youtube-dl 1t3Hbvflc40 -f bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best --merge-output-format mp4 --no-check-certificate --restrict-filenames -o 'G:/dataset/ope
nasl/OpenASL-main/data/raw-video/%(id)s.%(ext)s'
[youtube] 1t3Hbvflc40: Downloading webpage
WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests
[youtube] 1t3Hbvflc40: Downloading API JSON"

**Comment by chevalierNoir** [comment]
This seems an issue with youtube-dl. Using [yt-dlp](https://github.com/yt-dlp/yt-dlp) works fine. Will push a fix soon.

**Comment by Candice1995** [comment]
> 
I also have some problems when downloading and preprocessing the data.  

/OpenASL/raw-video/Mci9oyb5V2E.mp4: No such file or directory
Reading video clip: /tmp/tmp1zhzhh1b/tmp.mp4
  0%|                                                                                                                                                                                         | 0/98420 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "prep/crop_video.py", line 124, in <module>
    main()
  File "prep/crop_video.py", line 119, in main
    get_clip(args.raw, args.output, args.tsv, args.bbox, 0, 1, target_size=args.target_size, ffmpeg=args.ffmpeg)
  File "prep/crop_video.py", line 88, in get_clip
    W, H = frames_origin[0].shape[1], frames_origin[0].shape[0]
IndexError: list index out of range

Could you tell me why so strange? I can't solve it
